name: "Control ID Home Assistant MQTT"
description: "Integrates Control ID Events to Home Assistant."
version: "0.0.1"
slug: "control_id_mqtt"
init: false
services:
  - mqtt:need
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
host_network: true
options:
  sensor_expiration: 5
  control_id_user: admin
  control_id_pw: admin
  control_id_ip:
  control_id_monitor_port: "3009"
  control_id_name: "Control ID Face"
schema:
  mqtt_server: "str?"
  mqtt_user: "str?"
  mqtt_pw: "password?"
  control_id_user: "str?"
  control_id_pw: "password?"
  control_id_ip: "str?"
  control_id_home_assistant_ip: "str?"
  control_id_monitor_port: "str?"
  control_id_name: "str"
  sensor_expiration: "int"