name: "Control ID Home Assistant MQTT"
description: "Integrates Control ID Events to Home Assistant."
version: "0.0.1"
slug: "control_id_mqtt"
init: false
services:
  - mqtt:need
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  sensor_expiration: 5
  control_id_user: admin
  control_id_pw: admin
  control_id_ip:
  control_id_monitor_host:
  control_id_monitor_port:
schema:
  mqtt_server: "str?"
  mqtt_user: "str?"
  mqtt_pw: "password?"
  control_id_user: "str?"
  control_id_pw: "password?"
  control_id_ip: "str?"
  control_id_monitor_host: "str?"
  control_id_monitor_port: "str?"
  sensor_expiration: "int"